# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3UXcf25b_6VYbcdIpDJqLFNnBizobpE
"""

import streamlit as st
from text_summarization import summarize_text  # Import the summarize function

def main():
    # Title and description
    st.title("End-to-End Text Summarization and Analysis System")
    st.write("""
    This system can summarize large corpora of text, analyze sentiment, extract keywords, and perform topic modeling.
    Upload a text file or paste the content below to get started.
    """)

    # File uploader
    uploaded_file = st.file_uploader("Upload a text file", type=["txt"])
    
    # Text area input
    text_input = st.text_area("Or paste your text here", height=200)

    # Button for Summarization
    if st.button("Summarize"):
        if uploaded_file is not None:
            file_content = uploaded_file.read().decode("utf-8")
            summary = summarize_text(file_content)  # Call the summarization function
            st.write(summary)
        elif text_input:
            summary = summarize_text(text_input)  # Call the summarization function
            st.write(summary)
        else:
            st.write("Please upload a file or paste some text.")

    # Other buttons for Sentiment Analysis, Keyword Extraction, Topic Modeling
    if st.button("Analyze Sentiment"):
        st.write("Sentiment analysis results will be displayed here.")
        # Call sentiment analysis function here

    if st.button("Extract Keywords"):
        st.write("Extracted keywords will be displayed here.")
        # Call keyword extraction function here

    if st.button("Topic Modeling"):
        st.write("Topic modeling results will be displayed here.")
        # Call topic modeling function here

if __name__ == "__main__":
    main()
