# -*- coding: utf-8 -*-
"""text_summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nkK7j7Y39ESMCq75j6zqBNqp9JNkugp
"""

# First, install necessary libraries
!pip install transformers

from transformers import pipeline

# Function to perform text summarization
def summarize_text(text, max_length=150, min_length=40):
    summarizer = pipeline("summarization")
    summary = summarizer(text, max_length=max_length, min_length=min_length, do_sample=False)
    return summary[0]['summary_text']

# Example use (you can replace it with your text input in the main file)
if __name__ == "__main__":
    sample_text = """
    The quick brown fox jumps over the lazy dog. This sentence is a good example to show
    how text summarization works. The brown fox is not a real character but is often used
    in such examples to demonstrate text-related processes in machine learning or natural
    language processing tasks. We will use this as a placeholder.
    """
    summarized = summarize_text(sample_text)
    print(summarized)

